### ISSUE TITLE
How to trigger a flush on playback stream?

### ISSUE THREAD

**Issue by lhr0909** [janakj/pulseaudio.js#13]
Thank you for putting this lib together. I am curious how I can trigger a flush on a playback stream with this setup. I saw that there isn't such method written but the command is defined.

Thanks in advance!

**Comment by janakj** [comment]
Hi @lhr0909, sorry for responding so late! I am unsure what you mean by triggering a flush on a playback stream. When you create a playback stream, the stream starts playing immediately. If you would like to perform some action once the stream has finished playing, you can await the Promise returned by createPlaybackStream to get the playback object. That object emits events that you can subscribe to, for example:
```JavaScript
pa.createPlaybackStream({
    sampleSpec: {
        format: bitDepth === 16 ? PA_SAMPLE_FORMAT.S16LE : PA_SAMPLE_FORMAT.U8,
        rate: sampleRate,
        channels
    }
}).then(output => {
    output.once('finish', () => /* do something */);
    output.once('close', () => /* do something */);
    output.once('error', () => /* do something */);
});
```
