### ISSUE TITLE
Add support for `getSourceOutputs` and `getSinkInputs`

### ISSUE THREAD

**Issue by NebuPookins** [janakj/pulseaudio.js#3]
I would like to invoke PulseAudio's `pa_context_get_source_output_info_list` and `pa_context_get_sink_input_info_list` but this doesn't seem to currently be exposed by this library. 

I noticed we seem to have an enum for that command https://github.com/janakj/pulseaudio.js/blob/1c3a5071c878879617acf5193d487a839c84edb1/src/command.ts#L82 but parsing the packet doesn't seem to be implemented, and I'm having trouble finding the packet structure in PulseAudio to try to implement it myself.

**Comment by janakj** [comment]
PR would be welcome if you want to try to add the missing functionality yourself!

After a quick search, I found the function that assembles the packet structure for GET_SOURCE_OUTPUT_INFO_LIST  here: https://github.com/pulseaudio/pulseaudio/blob/7f4d7fcf5f6407913e50604c6195d0d5356195b1/src/pulsecore/protocol-native.c#L3440.

This is invoked repeatedly for each output from here: https://github.com/pulseaudio/pulseaudio/blob/7f4d7fcf5f6407913e50604c6195d0d5356195b1/src/pulsecore/protocol-native.c#L3609.

Hope that helps.

**Comment by janakj** [comment]
pa_context_get_sink_input_info is already implemented here: https://github.com/janakj/pulseaudio.js/blob/main/src/command.ts#L558-L587
and it should be trivial to implement the "List" variant.

See here for an an example of a "*List" command: https://github.com/janakj/pulseaudio.js/blob/main/src/command.ts#L471-L478

**Comment by janakj** [comment]
Implemented.
