### ISSUE TITLE
Change PA server

### ISSUE THREAD

**Issue by vidicunt** [janakj/pulseaudio.js#6]
Hello!

There's no option to change the PA server I'm trying to connect this client to.

**Comment by janakj** [comment]
You can pass an alternative socket path when creating the PulseAudio object via the sockPath parameter:
https://github.com/janakj/pulseaudio.js/blob/668ddec90f60d6add8b934787f0c74a9b620231e/src/client.ts#L117

By default the client tries to connect to `/run/user/${process.getuid()}/pulse/native`.

**Comment by vidicunt** [comment]
I tried
`
const pa = new PulseAudio({
  sockPath: "/run/pulse/pulseaudio.socket"
});
`

I tried multiple variations:
"unix:/run/pulse/pulseaudio.socket"
"/run/pulse/pulseaudio.socket"
"/run/pulse/"
"tcp:192.168.1.93:4317"

All give me the same error:
`Error: Disconnected from PulseAudio`

**Comment by janakj** [comment]
`const pa = new PulseAudio(undefined, undefined, "/run/pulse/pulseaudio.socket");`

**Comment by vidicunt** [comment]
Thank you very much and my apologies!
