### ISSUE TITLE
Can't try/catch pa.connect()

### ISSUE THREAD

**Issue by vidicunt** [janakj/pulseaudio.js#7]
pa.connect() cannot be caught in a try/catch in case a pulseaudio server is not online

**Comment by janakj** [comment]
I have no clue what you mean by that. Clearly, any JavaScript function can be enclosed in a try-catch statement.

**Comment by vidicunt** [comment]
I'm trying to make a while loop and retry connecting to a pulseaudio server until it's online. Putting pa.connect() in a try block always crashes the whole app which is pretty unusual.
Does it work for you?

**Comment by janakj** [comment]
What does "crashes the whole app which is pretty unusual" mean?

**Comment by vidicunt** [comment]
I'm using a node image in docker

**Comment by janakj** [comment]
Please open new issues for specific problems in the pulseaudio.js library only. I cannot help with generic JavaScript issues.
